#!/usr/bin/env python3

import csv
import os
import sys
from pathlib import Path, PosixPath
import numpy as np


def extract_value(mathematica_value : str):
    """
    Extracts string values from csv tables generated with Mathematica that sometimes have exponant writings and transform into float value
    """
    try : 
        value = float(mathematica_value)
        return value
    except ValueError:
        nb, exposant = mathematica_value.split('*^')
        value = float(nb)*10**(float(exposant))
        return value

def extract_curve(mathematica_list : str):
    """
    Extracts array of points of a stability curve generated by Murdoch_script_stability_diagram_tH2-tP1.nb under the form of an array of list of two values.
    """
    mathematica_list = mathematica_list[1:-1] # Remove { } 
    a,b,c,d = mathematica_list.split(',')
    arrayVP = np.array([extract_value(a),extract_value(b),extract_value(c),extract_value(d)])
    arrayVP = arrayVP.astype(float)
    return arrayVP

def extractVPs_Godfray(path_filename):
    """
    Loads data.csv from Mathematica scripts of stability diagram generation for Godfray system.
    
    Returns t_vals (all ratioT values), k_vals and GridVPs i.e. all 4 (or less) VP real part with axis 0:ratioT, axis1:k
    """
    
    nb_of_vals = 0
    kval_nb_found = False
    nb_of_kvals = 0

    ### FILE FIRST ANALYSIS : how many values ? how many k values per t value?
    with open(path_filename+'.csv', newline="") as csvfile:
        reader = csv.reader(csvfile)
        for i,row in enumerate(reader):
            if i==0:
                first_tval = float(row[0])
            if not kval_nb_found:
                tval = float(row[0])
                if tval == first_tval:
                    nb_of_kvals +=1
                else:
                    kval_nb_found = True
            nb_of_vals +=1
    
    # print(nb_of_vals)
    # print(nb_of_kvals)
    nb_of_tvals = int(nb_of_vals/nb_of_kvals)
    
    
    ### tvals, kvals extraction
    t_vals = []
    k_vals = []
    with open(path_filename+'.csv', newline="") as csvfile:
        reader = csv.reader(csvfile)
        for i,row in enumerate(reader):
            if float(row[0]) not in t_vals:
                t_vals.append(float(row[0]))
            if float(row[1]) not in k_vals:
                k_vals.append(float(row[1]))
    t_vals = np.array(t_vals) 
    k_vals = np.array(k_vals) 
    
    t_vals = t_vals[:-1] # In find_k_roots, mask will compare two consecutive values so will be of dimension Length-1
    k_vals = k_vals[:-1]

    ### VP extraction into a long array
    VPs = np.zeros((nb_of_vals, 2)) 
    with open(path_filename+'.csv', newline="") as csvfile:
        reader = csv.reader(csvfile)
        for i,row in enumerate(reader):
            VPs[i,:] = np.array(row)[2:]
    
    ### VP reshaping
    GridVPs = np.reshape(VPs, newshape = ((nb_of_tvals, nb_of_kvals, 2)))

    return t_vals, k_vals, GridVPs