#!/usr/bin/env python3

import csv
import os
import sys
from pathlib import Path, PosixPath
import numpy as np


def extract_value(mathematica_value : str):
    """
    Extracts string values from csv tables generated with Mathematica that sometimes have exponant writings and transform into float value
    """
    try : 
        value = float(mathematica_value)
        return value
    except ValueError:
        nb, exposant = mathematica_value.split('*^')
        value = float(nb)*10**(float(exposant))
        return value



def extract_curve(mathematica_list : str):
    """
    Extracts array of points of a stability curve generated by Murdoch_script_stability_diagram_tH2-tP1.nb and Murdoch_Equivalence_k_n under the form of a tuple of two values.
    """
    if mathematica_list == 'Missing["Filtered"]': # Missing value of the curve because of FindRoot failure
        return (np.nan,np.nan) 
    else:
        mathematica_list = mathematica_list[1:-1] # Remove { } 
        x,y = mathematica_list.split(',')
        x = extract_value(x)
        y = extract_value(y)
        return (x,y)
        


def extractVPs_Godfray(path : PosixPath,
                      nb_of_VP : int):
    """
    INPUT:
    path : complete path (with .csv) of data.csv file generated with Mathemata script. PosixPath type.
    
    Loads data.csv from Mathematica scripts of stability diagram generation for Godfray system. Raw data is a long array : for all couples (ratioT, k), the set of the nb_of_VP rightmost VPs is given. It has two dimensions.

    OUTPUT:
    Returns a large, 3-dimensional numpy array with t_vals (all ratioT values), k_vals and GridVPs i.e. all 4 (or less) VP real part with axis 0:ratioT, axis1:k
    """
    nb_of_vals = 0
    kval_nb_found = False
    nb_of_kvals = 0

    ### FIRST ANALYSIS : how many values ? how many k values per t value?
    with open(path, newline="") as csvfile:
        reader = csv.reader(csvfile)
        for i,row in enumerate(reader):
            if i==0:
                first_tval = float(row[0])
            if not kval_nb_found:
                tval = float(row[0])
                if tval == first_tval:
                    nb_of_kvals +=1
                else:
                    kval_nb_found = True
            nb_of_vals +=1
    
    # print(nb_of_vals)
    # print(nb_of_kvals)
    nb_of_tvals = int(nb_of_vals/nb_of_kvals)
    
    
    ### (unique) tvals, kvals extraction
    t_vals = []
    k_vals = []
    with open(path, newline="") as csvfile:
        reader = csv.reader(csvfile)
        for i,row in enumerate(reader):
            if float(row[0]) not in t_vals:
                t_vals.append(float(row[0]))
            if float(row[1]) not in k_vals:
                k_vals.append(float(row[1]))
    t_vals = np.array(t_vals) 
    k_vals = np.array(k_vals) 
    
    t_vals = t_vals[:-1] # In find_k_roots, mask will compare two consecutive values so will be of dimension Length-1
    k_vals = k_vals[:-1]

    ### VP extraction into a long array
    VPs = np.zeros((nb_of_vals, nb_of_VP)) 
    with open(path, newline="") as csvfile:
        reader = csv.reader(csvfile)
        for i,row in enumerate(reader):
            VPs[i,:] = np.array(row)[2:] # 2: because first two columns are ratioT, k
    
    ### VP reshaping into a 3dim array (tensor)
    GridVPs = np.reshape(VPs, newshape = ((nb_of_tvals, nb_of_kvals, nb_of_VP)))

    return t_vals, k_vals, GridVPs




def find_k_roots(t_values : np.ndarray,
                 k_values : np.ndarray,
                 GridVPs : np.ndarray, 
                 index_VP : int):
    """
    INPUT:
    t_values, k_values : unique values taken by ratioT and k (generated with extractVPs_Godfray).
    GridVPs : large array generated with extractVPs_Godfray
    index_VP : first (0) is the "rightmost" (largest), last (depends on the nb of VP extracted before) is typically the U curve on the right side of the stability diagram in Xu 2010.
    
    Generate stability curves, i.e. curves giving the k such that VP=0 for each value of ratioT.

    OUTPUT:
    np.ndarray of the k-root corresponding to each value in t_values np.ndarray
    """
    k_roots = np.zeros(t_values.shape[0])
    for i,t in enumerate(t_values):
        signchange = np.diff(np.sign(GridVPs[i,:,index_VP])) != 0
        if np.sum(signchange) == 0 :
            continue
        if np.sum(signchange) > 1 : 
            print("ERROR")
            break
        k_roots[i] = k_values[signchange][0] - 0.05 # k root is somewhere between x and x+1 knowing that here the step betweens x is 0.1
    k_roots[k_roots == 0.] = np.nan # Removing cases where no k root for given ratioT
    return k_roots